#!/usr/bin/env sh

QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-wayland;xcb}"
QT_AUTO_SCREEN_SCALE_FACTOR="${QT_AUTO_SCREEN_SCALE_FACTOR:-1}"
QT_WAYLAND_DISABLE_WINDOWDECORATION="${QT_WAYLAND_DISABLE_WINDOWDECORATION:-1}"
QT_QPA_PLATFORMTHEME="${QT_QPA_PLATFORMTHEME:-qt6ct}"
MOZ_ENABLE_WAYLAND="${MOZ_ENABLE_WAYLAND:-1}"
GDK_SCALE="${GDK_SCALE:-1}"
ELECTRON_OZONE_PLATFORM_HINT="${ELECTRON_OZONE_PLATFORM_HINT:-auto}"
HYPRLAND_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf"
HYPRLAND_NO_SD_NOTIFY=1
HYPRLAND_NO_SD_VARS=1

export ELECTRON_OZONE_PLATFORM_HINT GDK_SCALE MOZ_ENABLE_WAYLAND QT_QPA_PLATFORMTHEME \
    QT_WAYLAND_DISABLE_WINDOWDECORATION QT_QPA_PLATFORM QT_AUTO_SCREEN_SCALE_FACTOR \
    HYPRLAND_NO_SD_NOTIFY HYPRLAND_NO_SD_VARS HYPRLAND_CONFIG
