general {
    layout = dwindle
    gaps_in = 3
    gaps_out = 6, 4, 4, 4
    border_size = 1
    col.active_border = rgba(6f737aff)
    col.inactive_border = rgba(30343aff)
    resize_on_border = true
    allow_tearing = false
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = snappy, 0.4, 0.0, 0.2, 1.0
    bezier = linear, 0.0, 0.0, 1.0, 1.0

    animation = windows, 1, 1, snappy, slide
    animation = windowsIn, 1, 1, snappy, slide
    animation = windowsOut, 1, 1, snappy, slide
    animation = windowsMove, 1, 1, snappy, slide
    animation = border, 1, 2, linear
    animation = fade, 1, 2, linear
    animation = workspaces, 1, 2, snappy, slide
}

dwindle {
    preserve_split = true
}

misc {
    background_color = rgb(000000)
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
}
