env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto

source = ./monitors.conf
source = ./input.conf
source = ./appearance.conf
source = ./windowrules.conf
source = ./keybindings.conf
source = ./startup.conf
