$service = uwsm app -s b -t service

exec-once = $service -u waybar-minimal.service -d "Minimal Waybar" -- waybar
exec-once = $service -u hypridle-minimal.service -d "Minimal idle manager" -- hypridle
exec-once = $service -u hyprpolkitagent-minimal.service -d "PolicyKit agent" -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = $service -u cliphist-text-minimal.service -d "Text clipboard history" -- wl-paste --type text --watch cliphist store
exec-once = $service -u cliphist-image-minimal.service -d "Image clipboard history" -- wl-paste --type image --watch cliphist store
exec-once = $service -u nm-applet-minimal.service -d "Network tray menu" -- nm-applet --indicator
exec-once = $service -u blueman-applet-minimal.service -d "Bluetooth tray menu" -- blueman-applet
