windowrule {
    name = float_satty
    match:class = ^(satty)$
    float = true
    center = true
}

windowrule {
    name = float_blueman_manager
    match:class = ^(blueman-manager)$
    float = true
    size = 560 420
    center = true
}
